#!/usr/bin/env ruby
require_relative 'finder'

repo_name = ARGV[0]
finder = OkCuGit::Finder.new(repo_name)
contacts = finder.all_contributors
something = contacts.join("\n")
File.open("./input.txt","w") { |file| file.write(something) }
puts "Created 'input.txt'"

